name: dev-container-base

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: elvis404/dev-container-base
      IMAGE_TAG: 0.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        cd dev_containers/public/base
        docker build . -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_NAME }}:latest
    - name: Publish
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_NAME }}:latest
