name: openjdk:8-jre

# Trigger
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        cd openjdk/8-jre/
        docker build . -t elvis404/openjdk:8-jre
    - name: Publish
      run: docker push elvis404/openjdk:8-jre
