name: rocketmq-console:1.0.0

# Trigger
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Jar
      run: |
        mkdir $GITHUB_WORKSPACE/workspace/
        cd $GITHUB_WORKSPACE/workspace/
        wget https://github.com/apache/rocketmq-externals/archive/rocketmq-console-1.0.0.zip
        unzip rocketmq-console-1.0.0.zip
        cd rocketmq-externals-rocketmq-console-1.0.0/rocketmq-console/
        mvn clean package -Dmaven.test.skip=true
        mv target/rocketmq-console-ng-1.0.0.jar $GITHUB_WORKSPACE/rocketmq/rocketmq-console/

    - name: Build Image
      run: |
        cd $GITHUB_WORKSPACE/rocketmq/rocketmq-console/
        docker build . -t elvis404/rocketmq-console:1.0.0

    - name: Publish
      run: docker push elvis404/rocketmq-console:1.0.0
